### ISSUE TITLE
Table has more that one primary key

### ISSUE THREAD

**Issue by Vital77766688** [Arisophy/django-compositepk-model#7]
Hi, I like your approach to this issue.
However, I got an error saying that table has more than one primary key.

```
django.db.utils.OperationalError: table "CompanyBranch" has more than one primary key
sqlite3.OperationalError: table "CompanyBranch" has more than one primary key
```

I just copypasted code from readme for testing purposes. 
Is there anything that wasn't mentioned there?

**Comment by Arisophy** [comment]
Hi, Thanks for your comment.

This package is to approach "Lagacy" DB.
So, I didn't use "migration". I changed Test DB definitions.

[add "managed = False" to test models #8](https://github.com/Arisophy/django-compositepk-model/pull/8)

Create SQL is here.

[django-compositepk-model/compositepk-model/test/migration/Createtable.sql](https://github.com/Arisophy/django-compositepk-model/blob/main/compositepk-model/test/migration/Createtable.sql)
